@echo off
echo Digital Marketing Website - Render Deployment Preparation
echo ========================================================

echo Checking Python installation...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo Python is not installed or not in PATH
    pause
    exit /b 1
)

echo Checking pip installation...
pip --version >nul 2>&1
if %errorlevel% neq 0 (
    echo Pip is not installed or not in PATH
    pause
    exit /b 1
)

echo Installing requirements...
pip install -r requirements.txt
if %errorlevel% neq 0 (
    echo Failed to install requirements
    pause
    exit /b 1
)

echo Collecting static files...
python manage.py collectstatic --noinput
if %errorlevel% neq 0 (
    echo Failed to collect static files
    pause
    exit /b 1
)

echo.
echo Deployment preparation completed successfully!
echo.
echo Next steps for Render deployment:
echo 1. Commit and push your changes to GitHub
echo 2. Connect your repository to Render
echo 3. Render will use render.yaml for automatic deployment
echo.
echo Render will automatically:
echo  - Use Python 3.13.0
echo  - Install requirements from requirements.txt
echo  - Collect static files
echo  - Start the application with Gunicorn
echo.
echo Make sure to set these environment variables in Render:
echo  - SECRET_KEY (will be auto-generated by Render)
echo  - DEBUG = False
echo.
pause